package config

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/spf13/viper"
)

// Models holds paths for the three ML model files.
type Models struct {
	Whisper  string
	Speaker  string
	Emotion  string
}

// Config holds all application configuration.
type Config struct {
	Language       string
	Threshold      float64
	MatchThreshold float64
	Format         string
	Strategy       string
	Discover       bool
	LogLevel       string
	Threads        int
	Models         Models
	Vocabulary     []string // custom vocabulary for whisper prompt
}

// defaultModelsDir returns ~/.metr/models/
func defaultModelsDir() string {
	home, err := os.UserHomeDir()
	if err != nil {
		home = "."
	}
	return filepath.Join(home, ".metr", "models")
}

// Defaults returns a Config populated with sensible defaults.
func Defaults() Config {
	modelsDir := defaultModelsDir()
	return Config{
		Language:       "auto",
		Threshold:      0.8,
		MatchThreshold: 0.55,
		Format:         "txt",
		Strategy:  "max_similarity",
		Discover:  true,
		LogLevel:  "info",
		Threads:   runtime.NumCPU(),
		Models: Models{
			Whisper:  "",
			Speaker:  filepath.Join(modelsDir, "campplus_sv_zh-cn.onnx"),
			Emotion:  filepath.Join(modelsDir, "sensevoice-small-int8.onnx"),
		},
	}
}

// Load reads configuration with the following priority (highest to lowest):
//  1. Explicit config file at configPath
//  2. speakers/config.yaml inside speakersDir
//  3. Built-in defaults
//
// Either configPath or speakersDir may be empty string.
func Load(configPath, speakersDir string) (Config, error) {
	v := viper.New()

	// Set defaults.
	d := Defaults()
	v.SetDefault("language", d.Language)
	v.SetDefault("threshold", d.Threshold)
	v.SetDefault("match_threshold", d.MatchThreshold)
	v.SetDefault("format", d.Format)
	v.SetDefault("strategy", d.Strategy)
	v.SetDefault("discover", d.Discover)
	v.SetDefault("loglevel", d.LogLevel)
	v.SetDefault("threads", d.Threads)
	v.SetDefault("models.whisper", d.Models.Whisper)
	v.SetDefault("models.speaker", d.Models.Speaker)
	v.SetDefault("models.emotion", d.Models.Emotion)

	if configPath != "" {
		// Explicit config path takes highest priority.
		v.SetConfigFile(configPath)
		if err := v.ReadInConfig(); err != nil {
			return Config{}, err
		}
	} else if speakersDir != "" {
		// Try speakers/config.yaml as optional config.
		v.SetConfigName("config")
		v.SetConfigType("yaml")
		v.AddConfigPath(speakersDir)
		// Ignore error when file doesn't exist.
		_ = v.ReadInConfig()
	}

	cfg := Config{
		Language:       v.GetString("language"),
		Threshold:      v.GetFloat64("threshold"),
		MatchThreshold: v.GetFloat64("match_threshold"),
		Format:         v.GetString("format"),
		Strategy:   v.GetString("strategy"),
		Discover:   v.GetBool("discover"),
		LogLevel:   v.GetString("loglevel"),
		Threads:    v.GetInt("threads"),
		Vocabulary: v.GetStringSlice("vocabulary"),
		Models: Models{
			Whisper: v.GetString("models.whisper"),
			Speaker: v.GetString("models.speaker"),
			Emotion: v.GetString("models.emotion"),
		},
	}
	return cfg, nil
}

// SaveableConfig holds user-facing settings to write to config.yaml.
type SaveableConfig struct {
	Language       string   `yaml:"language"`
	Threshold      float64  `yaml:"threshold"`
	MatchThreshold float64  `yaml:"match_threshold"`
	Format         string   `yaml:"format"`
	Vocabulary     []string `yaml:"vocabulary,omitempty"`
}

// Save writes user-facing config values to a YAML file.
func Save(configPath string, sc SaveableConfig) error {
	var lines []string
	lines = append(lines, "# speakers/config.yaml")
	lines = append(lines, "# Auto-generated by metr transcribe")
	lines = append(lines, "")
	lines = append(lines, fmt.Sprintf("language: %q", sc.Language))
	lines = append(lines, fmt.Sprintf("threshold: %.2f", sc.Threshold))
	lines = append(lines, fmt.Sprintf("match_threshold: %.2f", sc.MatchThreshold))
	lines = append(lines, fmt.Sprintf("format: %q", sc.Format))
	if len(sc.Vocabulary) > 0 {
		lines = append(lines, "vocabulary:")
		for _, v := range sc.Vocabulary {
			lines = append(lines, fmt.Sprintf("  - %q", v))
		}
	}
	lines = append(lines, "")

	content := strings.Join(lines, "\n")
	return os.WriteFile(configPath, []byte(content), 0644)
}

// allFormats is the canonical list of supported output formats.
var allFormats = []string{"txt", "json", "srt"}

// ParseFormats parses a comma-separated format string into a slice of format names.
// The special value "all" expands to all supported formats.
func ParseFormats(format string) []string {
	if strings.EqualFold(strings.TrimSpace(format), "all") {
		result := make([]string, len(allFormats))
		copy(result, allFormats)
		return result
	}
	parts := strings.Split(format, ",")
	out := make([]string, 0, len(parts))
	for _, p := range parts {
		p = strings.TrimSpace(p)
		if p != "" {
			out = append(out, p)
		}
	}
	return out
}

// SupportedAudioExtensions returns the list of audio file extensions this tool handles.
func SupportedAudioExtensions() []string {
	return []string{".wav", ".mp3", ".m4a", ".flac", ".ogg", ".opus", ".aac", ".mp4", ".mkv", ".webm"}
}
